### ISSUE TITLE
Confusion about documentation

### ISSUE THREAD

**Issue by Volpone24** [CodLiver/Parallel-Programming-v2#1]
I saw your solution for openmp gauss Seidel and it's great but I am having few difficulties.

1. I don't understand which is the better version gauss2d_2 or gauss2d_4 and why.?

2. How are the two different?

3. Also, it would be helpful if you could write documentation for the main solver.

I also would be greatful if you could share your email for future correspondence.

**Comment by CodLiver** [comment]
Hello, 

Thanks for the issue. 

1) gauss2d_4 is slightly the better one. 

2) The gauss2d_4 has the "reduction" function in the solver where as gauss2d_2 has the old manual adaptation of the "reduction". Therefore, the compiler optimizes better for peak performance.

I have added the results for jacobi and gauss_seidel codes. You can see the slight improvement there. 

Hope it answers your question.

Regards,
CL
